### ISSUE TITLE
Keeping it always toggled on

### ISSUE THREAD

**Issue by ankitpal1029** [eliskah/tab-numbers#3]
personally i find it kind of annoying to press alt+t to see the tab numbers, is there any way to keep the extension always on?

edit: i did manage to keep the extension on without requiring to do a alt + t every time, 
maybe a toggle apart from alt + t that keeps the tab numbering on should solve my issue.

Great job on the extension though

**Comment by eliskah** [comment]
Thanks again for #4 solving this, just merged it!
